services:
  zktaccess:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    container_name: zktaccess
    restart: 'no'
    volumes:
      - ./.env:/app/.env
      - ./requirements.txt:/app/requirements.txt
      - ./requirements-dev.txt:/app/requirements-dev.txt
      - ./src:/app/src
      - ./tests:/app/tests
