services:
  zktaccess:
    build:
      context: . 
    platform: linux/amd64
    container_name: zktaccess
    restart: 'no'
    volumes:
      - ./.env:/app/.env
      - ./pyproject.toml:/app/pyproject.toml
      - ./src:/app/src
      - ./tests:/app/tests

