services:
  zktaccess:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    container_name: zktaccess
    restart: 'no'
    volumes:
      - ./.env:/app/.env
      - ./pyproject.toml:/app/pyproject.toml
      - ./src:/app/src
      - ./tests:/app/tests

